# Site settings
title: Krishna Kumar
description: A few things to know about Krishna.
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Krishna Kumar
user_description: Computer Science Undergrad. Interested in everything interesting. AI and Machine Learning enthusiast.
user_title: Data Engineer at Udacity
email: krishnaqmar@gmail.com
twitter_username: krishnaqmar4
github_username:  krishna-kumar456
gplus_username:  

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
